# Generated by Django 3.2.5 on 2021-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('At Home', 'At Home'), ('In Place', 'In Place')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
