# Generated by Django 3.2.5 on 2022-08-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220809_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category_name',
            new_name='name',
        ),
    ]
