# Generated by Django 3.2.5 on 2021-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Please enter your details', max_length=500),
            preserve_default=False,
        ),
    ]
