# Generated by Django 3.2.5 on 2021-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210709_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
