# Generated by Django 3.2.5 on 2021-07-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
