# Generated by Django 3.2.5 on 2021-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('At Home', 'At Home'), ('In Place', 'In Place'), ('Online', 'Online')], max_length=15),
        ),
    ]
