# Generated by Django 3.2.5 on 2021-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
            preserve_default=False,
        ),
    ]
