# Generated by Django 3.2.5 on 2021-07-13 01:01

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=service.models.image_upload),
        ),
    ]
