# Generated by Django 3.2.5 on 2021-07-16 01:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20210716_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug_view',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=True, null=True, populate_from='title', unique=True),
        ),
    ]
