# Generated by Django 3.2.5 on 2021-07-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
