# Generated by Django 3.2.5 on 2021-07-30 13:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, default='', editable=True, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
