# Generated by Django 3.2.5 on 2021-07-30 14:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, populate_from='title', unique=True),
        ),
    ]
